[package]
name = "python_lib_tut"
version = "0.1.0"
authors = ["mycognosist <gnomad@cryptolab.net>"]

[lib]
name = "status"
crate-type = ["cdylib"]

[dependencies]
cpython="*"
# cpython = "0.7"
# pyo3 = { version = "0.17.3", features = ["extension-module"] }

